FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# We use the $PORT and $HOST variables that Docker Compose injected!
CMD ["sh", "-c", "uvicorn main:app --host $HOST --port $PORT"]